version: '3.8'

services:
  bravia-control-center:
    image: anumac/bravia-control-center:latest
    build: .
    container_name: bravia-control-center
    restart: unless-stopped
    network_mode: host
    ports:
      - "8888:8888"
    environment:
      - ADB_TARGET=192.168.2.122:5555
    volumes:
      - bravia_data:/app/data

volumes:
  bravia_data:
